services:

  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"

  fastapi:
    build: .
    container_name: fastapi-app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build: .
    container_name: celery-worker
    command: celery -A app.celery_worker.celery worker --loglevel=info
    depends_on:
      - redis